spring.application.name=user-service
server.port=8081

# In-memory H2 database ? lives only while the app is running
spring.datasource.url=jdbc:h2:mem:user_db
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Tell this service where the Eureka server is running
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
